server:
  port: 8003

spring:
  application:
    name: cloud-provider-payment
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://192.168.211.131:33065/itcast?useUnicode=true&characterEncoding-utr-8&useSSL=false
      username: root
      password: 123456
  cloud:
      zookeeper:
        connect-string: 192.168.211.131:2181,192.168.211.131:2182,192.168.211.131:2183
