server:
  port: 80

spring:
  application:
    name:  cloud-consumer-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://euk1.com:7001/eureka,http://euk2.com:7002/eureka
