server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.211.131:33065/itcast?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzl.study.cloudcommon.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://euk1.com:7001/eureka,http://euk2.com:7002/eureka
  instance:
    instance-id: payment8001
    ## 访问路径可以显示ip地址
    prefer-ip-address: true
    ## Eureka客户端向服务端发送心跳的间隔时间，默认为30s
    lease-renewal-interval-in-seconds: 1
    ## Eureka服务器在收到最后一次心跳后等待时间上限，默认为90s
    lease-expiration-duration-in-seconds: 2